all: ts_1_synthetic_data.md ts_2_analysis.md

ts_1_synthetic_data.md: ts_1_synthetic_data.ipynb 
	jupytext --to myst ts_1_synthetic_data.ipynb 

ts_2_analysis.md: ts_2_analysis.ipynb 
	jupytext --to myst ts_2_analysis.ipynb 

